<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>JustinCredible.I8080Disassembler</RootNamespace>
    <Version>1.0.0</Version>
    <NoWarn>CS0618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\intel8080\intel8080.csproj" />
  </ItemGroup>

</Project>
